services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "host.docker.internal:5678"
      - "--domain=${NGROK_DOMAIN:-}"
    ports:
      - "4040:4040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ngrok-network

networks:
  ngrok-network:
    driver: bridge