services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: Oregon  # or your preferred region
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: localhost
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        value: n8n
      - key: DB_POSTGRESDB_PASSWORD
        value: n8n
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1